// file: src/next/examples/all-in-one.tsx
// Navigation tree variants for testing various templates
// Sample navigation tree data (normally generated by rr-builder)

// Dashboard navigation trees
const dashboard = {
  simple: {
    main: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "/dashboard",
        iconName: "LayoutDashboard",
      },
      {
        id: "analytics",
        label: "Analytics",
        path: "/analytics",
        iconName: "BarChart",
      },
      {
        id: "settings",
        label: "Settings",
        path: "/settings",
        iconName: "Settings",
      },
    ],
  },
  complex: {
    main: [
      {
        id: "dashboard",
        label: "Dashboard",
        path: "/dashboard",
        iconName: "LayoutDashboard",
      },
      {
        id: "analytics",
        label: "Analytics",
        path: "/analytics",
        iconName: "BarChart",
        children: [
          {
            id: "overview",
            label: "Overview",
            path: "/analytics/overview",
            iconName: "PieChart",
          },
          {
            id: "reports",
            label: "Reports",
            path: "/analytics/reports",
            iconName: "FileText",
          },
        ],
      },
      {
        id: "users",
        label: "User Management",
        path: "/users",
        iconName: "Users",
        children: [
          {
            id: "list",
            label: "User List",
            path: "/users/list",
            iconName: "List",
          },
          {
            id: "roles",
            label: "Roles",
            path: "/users/roles",
            iconName: "Shield",
          },
        ],
      },
      {
        id: "settings",
        label: "Settings",
        path: "/settings",
        iconName: "Settings",
      },
    ],
  },
};
// Documentation navigation trees
const docs = {
  simple: {
    main: [
      {
        id: "introduction",
        label: "Introduction",
        path: "/introduction",
        iconName: "Book",
      },
      {
        id: "getting-started",
        label: "Getting Started",
        path: "/getting-started",
        iconName: "Play",
      },
      {
        id: "components",
        label: "Components",
        path: "/components",
        iconName: "Layers",
      },
    ],
  },
  complex: {
    main: [
      {
        id: "introduction",
        label: "Introduction",
        path: "/introduction",
        iconName: "Book",
      },
      {
        id: "getting-started",
        label: "Getting Started",
        path: "/getting-started",
        iconName: "Play",
        children: [
          {
            id: "installation",
            label: "Installation",
            path: "/getting-started/installation",
          },
          {
            id: "basic-usage",
            label: "Basic Usage",
            path: "/getting-started/basic-usage",
          },
          {
            id: "configuration",
            label: "Configuration",
            path: "/getting-started/configuration",
          },
        ],
      },
      {
        id: "components",
        label: "Components",
        path: "/components",
        iconName: "Layers",
        children: [
          {
            id: "navigator",
            label: "Navigator",
            path: "/components/navigator",
          },
          { id: "header", label: "Header", path: "/components/header" },
          { id: "drawer", label: "Drawer", path: "/components/drawer" },
        ],
      },
      {
        id: "hooks",
        label: "Hooks",
        path: "/hooks",
        iconName: "Anchor",
        children: [
          {
            id: "use-navigator",
            label: "useNavigator",
            path: "/hooks/use-navigator",
          },
          { id: "use-theme", label: "useTheme", path: "/hooks/use-theme" },
        ],
      },
    ],
  },
};
// E-commerce navigation trees
const ecommerce = {
  simple: {
    store: [
      {
        id: "clothing",
        label: "Clothing",
        path: "/clothing",
        iconName: "ShoppingBag",
        displayType: "megamenu",
      },
      {
        id: "electronics",
        label: "Electronics",
        path: "/electronics",
        iconName: "Smartphone",
        displayType: "megamenu",
      },
      {
        id: "home",
        label: "Home & Garden",
        path: "/home",
        iconName: "Home",
        displayType: "megamenu",
      },
    ],
  },
  complex: {
    store: [
      {
        id: "clothing",
        label: "Clothing",
        path: "/clothing",
        iconName: "ShoppingBag",
        displayType: "megamenu",
        children: [
          {
            id: "mens",
            label: "Men's",
            path: "/clothing/mens",
            parent: "clothing",
            group: "categories",
          },
          {
            id: "womens",
            label: "Women's",
            path: "/clothing/womens",
            parent: "clothing",
            group: "categories",
          },
          {
            id: "kids",
            label: "Kids",
            path: "/clothing/kids",
            parent: "clothing",
            group: "categories",
          },
          {
            id: "tshirt",
            label: "Summer T-Shirt",
            path: "/clothing/tshirt",
            parent: "clothing",
            group: "featured",
          },
          {
            id: "jeans",
            label: "Slim Fit Jeans",
            path: "/clothing/jeans",
            parent: "clothing",
            group: "featured",
          },
        ],
      },
      {
        id: "electronics",
        label: "Electronics",
        path: "/electronics",
        iconName: "Smartphone",
        displayType: "megamenu",
        children: [
          {
            id: "phones",
            label: "Phones",
            path: "/electronics/phones",
            parent: "electronics",
            group: "categories",
          },
          {
            id: "laptops",
            label: "Laptops",
            path: "/electronics/laptops",
            parent: "electronics",
            group: "categories",
          },
          {
            id: "audio",
            label: "Audio",
            path: "/electronics/audio",
            parent: "electronics",
            group: "categories",
          },
          {
            id: "headphones",
            label: "Wireless Earbuds",
            path: "/electronics/headphones",
            parent: "electronics",
            group: "featured",
          },
          {
            id: "watch",
            label: "Smart Watch",
            path: "/electronics/watch",
            parent: "electronics",
            group: "featured",
          },
        ],
      },
      {
        id: "home",
        label: "Home & Garden",
        path: "/home",
        iconName: "Home",
        displayType: "megamenu",
      },
      { id: "beauty", label: "Beauty", path: "/beauty", iconName: "Heart" },
      {
        id: "sports",
        label: "Sports",
        path: "/sports",
        iconName: "Activity",
      },
    ],
  },
};

// News navigation trees
const news = {
  simple: {
    main: [
      { id: "home", label: "Home", path: "/", iconName: "Home", end: true },
      { id: "foryou", label: "For you", path: "/foryou", iconName: "Star" },
      {
        id: "following",
        label: "Following",
        path: "/following",
        iconName: "Bell",
      },
    ],
    categories: [
      { id: "us", label: "U.S.", path: "/section/us", iconName: "Flag" },
      {
        id: "world",
        label: "World",
        path: "/section/world",
        iconName: "Globe",
      },
      {
        id: "local",
        label: "Local",
        path: "/section/local",
        iconName: "MapPin",
      },
    ],
  },
  complex: {
    main: [
      { id: "home", label: "Home", path: "/", iconName: "Home", end: true },
      { id: "foryou", label: "For you", path: "/foryou", iconName: "Star" },
      {
        id: "following",
        label: "Following",
        path: "/following",
        iconName: "Bell",
      },
      {
        id: "showcase",
        label: "News Showcase",
        path: "/showcase",
        iconName: "Layout",
      },
      {
        id: "saved",
        label: "Saved searches",
        path: "/saved",
        iconName: "Bookmark",
      },
    ],
    categories: [
      {
        id: "us",
        label: "U.S.",
        path: "/section/us",
        iconName: "Flag",
        contextActions: [
          { id: "star", label: "Save", iconName: "Star" },
          { id: "share", label: "Share", iconName: "Share" },
        ],
      },
      {
        id: "world",
        label: "World",
        path: "/section/world",
        iconName: "Globe",
      },
      {
        id: "local",
        label: "Local",
        path: "/section/local",
        iconName: "MapPin",
      },
      {
        id: "business",
        label: "Business",
        path: "/section/business",
        iconName: "Briefcase",
      },
      {
        id: "technology",
        label: "Technology",
        path: "/section/technology",
        iconName: "Cpu",
      },
      {
        id: "entertainment",
        label: "Entertainment",
        path: "/section/entertainment",
        iconName: "Film",
      },
      {
        id: "sports",
        label: "Sports",
        path: "/section/sports",
        iconName: "Activity",
      },
      {
        id: "science",
        label: "Science",
        path: "/section/science",
        iconName: "Flask",
      },
      {
        id: "health",
        label: "Health",
        path: "/section/health",
        iconName: "Health",
      },
    ],
  },
};

export default {
  dashboard, docs, ecommerce, news
};
